# Wearables collections to scrape
RECTREK_URL = "https://www.outdoorvoices.com/collections/rectrek"
CLOUDKNIT_URL = "https://www.outdoorvoices.com/collections/cloudknit"
LIGHTSPEED_URL = "https://www.outdoorvoices.com/collections/lightspeed"
MIGHTY_COTTON_URL = "https://www.outdoorvoices.com/collections/mighty-cotton"
ORGANIC_COTTON_JERSEY_URL = "https://www.outdoorvoices.com/collections/organic-cotton-jersey"
ORGANIC_COTTON_TERRY_URL = "https://www.outdoorvoices.com/collections/organic-cotton-terry"
BEACHTREE_COTTON_URL = "https://www.outdoorvoices.com/collections/beachtree-cotton"
NIMBUS_COTTON_URL = "https://www.outdoorvoices.com/collections/nimbus-cotton"
TEXTURED_COMPRESSION_URL = "https://www.outdoorvoices.com/collections/textured-compression"
TECH_SWEAT_URL = "https://www.outdoorvoices.com/collections/tech-sweat"
THINKFAST_URL = "https://www.outdoorvoices.com/collections/thinkfast"
FREEFORM_URL = "https://www.outdoorvoices.com/collections/freeform"
PRIMOFLEECE_URL = "https://www.outdoorvoices.com/collections/primofleece"
MEGAFLEECE_URL = "https://www.outdoorvoices.com/collections/megafleece"
SEAMLESS_URL = "https://www.outdoorvoices.com/collections/seamless-rib"
GRIDTEK_URL = "https://www.outdoorvoices.com/collections/gridtek"
RECFLEECE_URL = "https://www.outdoorvoices.com/collections/recfleece"
TSW_URL = "https://www.outdoorvoices.com/collections/train-stretch-woven"
REC_POLY_URL = "https://www.outdoorvoices.com/collections/rec-poly"
FROSTKNIT_URL = "https://www.outdoorvoices.com/collections/frostknit"
SOFTSHIELD_URL = "https://www.outdoorvoices.com/collections/softshield"

# Wearables fabrics to scrape
FABRICS_URL = "https://www.outdoorvoices.com/pages/fabrics"
